"""
test_edge_cases.py

STEP 6: Edge-case and user-scenario tests for the Step 6 application layer,
using the synthetic PDFs generated by scripts/generate_edge_case_pdfs.py.

These simulate real user actions against the FastAPI backend:
  - uploading a blank/scanned PDF
  - uploading a PDF with no ESG content
  - uploading a corrupted / non-PDF file
  - uploading a renamed copy of the sample PDF (mock-mode limitation)
  - uploading a large multi-page PDF
  - boundary values for top_k
  - unknown claim lookups
  - the curated dataset demo (guaranteed ALIGN/CONTRADICT/INSUFFICIENT_EVIDENCE)

All offline, no network/API keys required.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

fastapi = pytest.importorskip("fastapi")
from fastapi.testclient import TestClient

from app.api.main import app
from app.api.pipeline import (
    PipelineError,
    analyze_pdf_file,
    build_audit_records,
    load_dataset_claims,
)

client = TestClient(app)

EDGE_CASE_DIR = PROJECT_ROOT / "data" / "sample_pdfs" / "edge_cases"


def _edge_case(name: str) -> Path:
    path = EDGE_CASE_DIR / name
    if not path.exists():
        pytest.skip(f"Run `python scripts/generate_edge_case_pdfs.py` first (missing {name})")
    return path


# ---------------------------------------------------------------------------
# User scenario: uploads a scanned/image-only report (no extractable text)
# ---------------------------------------------------------------------------


def test_blank_scanned_pdf_reports_no_extractable_text():
    path = _edge_case("blank_scanned_report.pdf")
    with path.open("rb") as f:
        resp = client.post(
            "/analyze",
            data={"use_demo": "false", "mode": "mock"},
            files={"file": ("blank_scanned_report.pdf", f, "application/pdf")},
        )
    assert resp.status_code == 200
    body = resp.json()
    assert body["status"] == "no_claims"
    assert "no extractable text" in body["message"].lower()
    assert body["summary"]["total_claims"] == 0
    # Regression: the response must echo the ORIGINAL uploaded filename, never
    # the server's internal tempfile name (found via live curl testing).
    assert body["source_document"] == "blank_scanned_report.pdf"
    assert not body["source_document"].startswith("tmp")


def test_analyze_response_echoes_original_filename_not_tempfile_name():
    """The server saves uploads to a NamedTemporaryFile before parsing; the API
    response must report the filename the user actually uploaded, not the
    server-generated temp path. Caught via live HTTP testing, not TestClient."""
    path = _edge_case("unrelated_content.pdf")
    with path.open("rb") as f:
        resp = client.post(
            "/analyze",
            data={"use_demo": "false", "mode": "mock"},
            files={"file": ("my_company_report_2025.pdf", f, "application/pdf")},
        )
    assert resp.status_code == 200
    assert resp.json()["source_document"] == "my_company_report_2025.pdf"


# ---------------------------------------------------------------------------
# User scenario: uploads a real, readable PDF with no ESG content
# ---------------------------------------------------------------------------


def test_unrelated_content_pdf_reports_no_claims_extracted():
    path = _edge_case("unrelated_content.pdf")
    with path.open("rb") as f:
        resp = client.post(
            "/analyze",
            data={"use_demo": "false", "mode": "mock"},
            files={"file": ("unrelated_content.pdf", f, "application/pdf")},
        )
    assert resp.status_code == 200
    body = resp.json()
    assert body["status"] == "no_claims"
    assert body["page_count"] >= 1


# ---------------------------------------------------------------------------
# User scenario: uploads a corrupted / fake PDF
# ---------------------------------------------------------------------------


def test_corrupted_pdf_returns_clean_422_not_a_crash():
    path = _edge_case("corrupted_not_a_real_pdf.pdf")
    with path.open("rb") as f:
        resp = client.post(
            "/analyze",
            data={"use_demo": "false", "mode": "mock"},
            files={"file": ("corrupted_not_a_real_pdf.pdf", f, "application/pdf")},
        )
    assert resp.status_code == 422
    assert "detail" in resp.json()


# ---------------------------------------------------------------------------
# User scenario: renames the sample PDF, expects it NOT to be silently
# recognized (mock mode must never guess by content).
# ---------------------------------------------------------------------------


def test_renamed_sample_pdf_does_not_get_canned_claims():
    path = _edge_case("renamed_sample_report.pdf")
    with path.open("rb") as f:
        resp = client.post(
            "/analyze",
            data={"use_demo": "false", "mode": "mock"},
            files={"file": ("renamed_sample_report.pdf", f, "application/pdf")},
        )
    assert resp.status_code == 200
    body = resp.json()
    assert body["status"] == "no_claims"


# ---------------------------------------------------------------------------
# User scenario: uploads a longer multi-page report
# ---------------------------------------------------------------------------


def test_large_multi_page_pdf_parses_all_pages():
    path = _edge_case("large_multi_page_report.pdf")
    with path.open("rb") as f:
        resp = client.post(
            "/analyze",
            data={"use_demo": "false", "mode": "mock"},
            files={"file": ("large_multi_page_report.pdf", f, "application/pdf")},
        )
    assert resp.status_code == 200
    body = resp.json()
    assert body["page_count"] == 12


# ---------------------------------------------------------------------------
# Boundary values
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("top_k", [1, 5, 10])
def test_demo_dataset_various_top_k(top_k):
    resp = client.get("/demo/dataset", params={"top_k": top_k})
    assert resp.status_code == 200
    body = resp.json()
    for record in body["audit_records"]:
        rr = record.get("retrieval_result")
        if rr:
            assert len(rr["evidence"]) <= top_k


def test_analyze_pdf_file_with_top_k_zero_returns_no_evidence():
    from app.api.pipeline import SAMPLE_PDF_PATH

    result = analyze_pdf_file(
        pdf_path=SAMPLE_PDF_PATH,
        company_hint="GreenLeaf Industries Ltd.",
        mode="mock",
        top_k=0,
        is_bundled_sample=True,
    )
    for record in result["audit_records"]:
        rr = record.get("retrieval_result")
        if rr:
            assert rr["evidence"] == []


# ---------------------------------------------------------------------------
# Claim lookup edge cases
# ---------------------------------------------------------------------------


def test_get_claim_with_malformed_id_returns_404_not_500():
    resp = client.get("/claims/not-a-real-format")
    assert resp.status_code == 404


def test_get_claim_empty_string_routes_to_not_found():
    resp = client.get("/claims/ ")
    assert resp.status_code == 404


# ---------------------------------------------------------------------------
# Full-dataset demo: verifies all three verdict types are actually reachable
# ---------------------------------------------------------------------------


def test_dataset_demo_produces_all_three_verdict_types():
    resp = client.get("/demo/dataset")
    assert resp.status_code == 200
    verdicts = {
        r["verification_result"]["verdict"]
        for r in resp.json()["audit_records"]
        if r.get("verification_result")
    }
    assert {"ALIGN", "CONTRADICT", "INSUFFICIENT_EVIDENCE"}.issubset(verdicts)


def test_not_checkable_claims_have_no_verification_or_risk_score():
    claims = load_dataset_claims()
    records = build_audit_records(claims, top_k=5, use_semantic=False)
    not_checkable = [
        r for r in records if r.checkability_result.checkability.value == "NOT_CHECKABLE"
    ]
    assert not_checkable, "Dataset should contain at least one NOT_CHECKABLE claim"
    for r in not_checkable:
        assert r.verification_result is None
        assert r.risk_score_result is None
        assert r.retrieval_result is None


# ---------------------------------------------------------------------------
# Unknown / missing dataset claim id at the pipeline level
# ---------------------------------------------------------------------------


def test_analyze_dataset_rejects_unknown_and_mixed_claim_ids():
    from app.api.pipeline import analyze_dataset

    with pytest.raises(PipelineError):
        analyze_dataset(claim_ids=["CLM-999-DOES-NOT-EXIST"])

    # A mix of one real + one fake id should keep only the real one.
    result = analyze_dataset(claim_ids=["CLM-001", "CLM-999-DOES-NOT-EXIST"])
    assert len(result["audit_records"]) == 1
    assert result["audit_records"][0]["claim_id"] == "CLM-001"
